services:
  mongo-database:
    image: mongo:7.0.0
    container_name: mongo-database
    ports:
      - "4002:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin


  arithmetic-service:
    image: arithmetic-service
    build:
      context: ../arithmetic-service
      dockerfile: Dockerfile
    container_name: arithmetic-service
    ports:
      - "4000:3000"
    environment:
      - PORT=3000
    restart: "no"

  azure-storage:
    image: azure-storage
    build:
      context: ../azure-storage
      dockerfile: Dockerfile
    container_name: azure-storage
    ports:
      - "4001:3000"
    environment:
      - PORT=3000
      - STORAGE_ACCOUNT_NAME=practicums
      - STORAGE_ACCESS_KEY=your_access_key
    restart: "no"